<?php

/**
 * This module was developed with initial funding from the NSF EPsCOR Grant.  Currently, the module is being maintained with funding from the NASA ACCESS Grant.
 * Copyright (c) 2013, Information Technology & Systems Center.  University of Alabama in Huntsville
 * All rights reserved.
 * Redistribution and use of the module, with or without modification, are permitted with proper credit to Information Technology & Systems Center,  University of Alabama in Huntsville.
 */

/**
 * @file
 * metadata_catalog.features.conditional_fields.inc
 */

/**
 * Implements hook_conditional_fields_default_fields().
 */
function metadata_catalog_conditional_fields_default_fields() {
  $items = array();

  return $items;
}
